---
title: Barbican Community Centre
email: thebarbicancommunitycenter@gmail.com
description: The People of York transforming land for the good of community, by whatever
  means works.
baseurl: ''
url: https://barbican.earth
theme: jekyll-rebellion
permalink: pretty
donate: https://www.gofundme.com/f/barbican-community-centre
logo: "/uploads/bcc-logo.png"
logo_light: "/uploads/bcc-logo-light.svg"
logo_square: "/uploads/logo-square.png"
brand_color: "#fff035"
accent_color: black
invert_accent_text: true
bold_font: Raleway-Bold
font: Raleway
instagram: https://www.instagram.com/barbican_community_centre/
twitter: https://twitter.com/barbican_cc
facebook: https://www.facebook.com/Barbican-Community-Centre-105558228443405/
riseup_listname: barbicancommunitycentre
copyright_notice: ''
collections:
  posts:
    permalink: "/news/:title/"
defaults:
- scope:
    path: google1c899b51019de383.html
  values:
    sitemap: false
- scope:
    path: admin/index.html
  values:
    sitemap: false
map:
  lat: "53.9574171"
  lng: "-1.0900804"
plugins:
- jekyll-feed
- jekyll-liquify
- jekyll-leaflet
- jekyll-sitemap
